In [31]:
import numpy as np
from copy import deepcopy

In [23]:
def matrix_multiply(A, B):
    if len(A[0]) != len(B):
        raise ValueError("Number of columns in the first matrix must equal the number of rows in the second matrix.")

    result = []
    for i in range(len(A)):
        row = []
        for j in range(len(B[0])):
            sum = 0
            for k in range(len(B)):
                sum += A[i][k] * B[k][j]
            row.append(sum)
        result.append(row)

    return np.array(result)

In [6]:
def reduce_to_rref(matrix):
    unit_matrix = [[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]]
    lead = 0
    rowCount = len(matrix)
    columnCount = len(matrix[0])

    for r in range(rowCount):
        if lead >= columnCount:
            return matrix
        i = r
        while matrix[i][lead] == 0:
            i += 1
            if i == rowCount:
                i = r
                lead += 1
                if columnCount == lead:
                    return matrix
        matrix[i], matrix[r] = matrix[r], matrix[i]
        unit_matrix[i], unit_matrix[r] = unit_matrix[r], unit_matrix[i]

        lv = matrix[r][lead]
        matrix[r] = [mrx / float(lv) for mrx in matrix[r]]
        unit_matrix[r] = [mrx / float(lv) for mrx in unit_matrix[r]]

        for i in range(rowCount):
            if i != r:
                lv = matrix[i][lead]
                matrix[i] = [iv - lv*rv for rv, iv in zip(matrix[r], matrix[i])]
                unit_matrix[i] = [iv - lv*rv for rv, iv in zip(unit_matrix[r], unit_matrix[i])]
        lead += 1
    return matrix, unit_matrix


In [33]:
A = [[0, 1, 2],
      [1, 0, 3],
      [4, -3, 8]]

A_copy = deepcopy(A)
rref_matrix, inverse_matrix = reduce_to_rref(A_copy)
print("RREF of A|I:")
for row in rref_matrix:
    print(row)

print("\nInverse of A")
for row in inverse_matrix:
    print(row)

RREF of A|I:
[1.0, 0.0, 0.0]
[0.0, 1.0, 0.0]
[0.0, 0.0, 1.0]

Inverse of A
[-4.5, 7.0, -1.5]
[-2.0, 4.0, -1.0]
[1.5, -2.0, 0.5]


In [34]:
print("Product of Original matrix & its inverse:\n",matrix_multiply(A, inverse_matrix))

Product of Original matrix & its inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
