<a href="https://colab.research.google.com/github/KayalvizhiT513/Linear-Algebra-The-Coding-Way/blob/main/Diagonalization%20of%20Symmetric%20Matrices/Diagonalization_SymmetricNotebook1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [11]:
def is_near_equal(A, B, tol=1e-5):
  """
  Checks if two matrices are element-wise near equal within a tolerance.

  Args:
      A: First matrix.
      B: Second matrix.
      tol: Tolerance level (default: 1e-5).

  Returns:
      True if matrices are near equal, False otherwise.
  """
  return np.abs(A - B).max() <= tol

In [13]:
def Is_orthonormal(A):
    # Calculate eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eig(A)

    # Check if eigenvectors are orthonormal
    eigenvector_product_matrix = np.dot(eigenvectors.T, eigenvectors)
    print("Eigenvector Product Matrix: \n",eigenvector_product_matrix)
    is_orthonormal = is_near_equal(np.eye(3), eigenvector_product_matrix)

    # Print the results
    print("\nEigenvalues:")
    print(eigenvalues)
    print("\nEigenvectors:")
    print(eigenvectors)
    print("\nAre eigenvectors orthonormal?:", is_orthonormal)


In [14]:
# Define the symmetric matrix
A = np.array([[6, -2, -1],
              [-2,  6, -1],
              [-1, -1,  5]])

# Function call
Is_orthonormal(A)

Eigenvector Product Matrix: 
 [[ 1.00000000e+00 -8.83728434e-17 -1.12180787e-16]
 [-8.83728434e-17  1.00000000e+00 -4.44217880e-16]
 [-1.12180787e-16 -4.44217880e-16  1.00000000e+00]]

Eigenvalues:
[3. 8. 6.]

Eigenvectors:
[[ 5.77350269e-01  7.07106781e-01 -4.08248290e-01]
 [ 5.77350269e-01 -7.07106781e-01 -4.08248290e-01]
 [ 5.77350269e-01 -2.79509395e-16  8.16496581e-01]]

Are eigenvectors orthonormal?: True


In [17]:
# Define the Asymmetric matrix
A1 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

# Function call
Is_orthonormal(A1)

Eigenvector Product Matrix: 
 [[ 1.00000000e+00 -2.73434371e-01  9.26731829e-17]
 [-2.73434371e-01  1.00000000e+00 -1.00862125e-15]
 [ 9.26731829e-17 -1.00862125e-15  1.00000000e+00]]

Eigenvalues:
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

Are eigenvectors orthonormal?: False
